saveExact: true
engineStrict: true
minimumReleaseAge: 1440
minimumReleaseAgeExcludePrune: true
trustPolicy: "no-downgrade"
trustPolicyExcludePrune: true
allowBuilds:
  "@prisma/engines": true
  msgpackr-extract: true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - framer-motion@14.0.0
  - motion-dom@14.0.0
  - motion@14.0.0
  - "@types/node@24.19.1"
  - motion-utils@14.0.0
